name: kiss
description: A universal development framework for Dart.
version: 0.0.1
repository: https://github.com/dart-kiss/kiss

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
